#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsd5C9uNSrtZCtOVlpo/Tfqxloh0ZKsp1F2VZ9dtEjA4XaEaXc4ur6LILTtn1bMRiSRoX3M2FjW3aZeRb/0qrV64bU7jSM4hrWlH6n+7rhc9P+wMZI6xbpSUSUFehx2/4zIRnL1GmHlyYZ3Df7xN+w6EkjJdP0UW42Cf9wrK/ARTwRXpOtklcbBwWDdtC26CXp9CygCwXDHtkyPZTmO7d/jV2zKRWfrbyd/q+WJeAPkjeKzX8Cm8z463gS+q41ayeXLHInAf9CVKjqod/cW5ahM9tIy09OEqik89J8i9m+e75l07UVbLV85uiApIFveoX8x0pvxNrvutKYgnRnu3bZ aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  
  
write_files:
  - path: /var/www/html/image.php
    content: |
        <?php 
        $ihrname = "Joel"; ?>
        <html>
        <head>
        <title><?php echo($ihrname) ?></title>
        </head>
        <body>
            Hier sieht man einen hellblauen Himmel, welches leicht bewölkt ist. An der Steinküste stehen Palmen.
        <br />
        <img src="https://joelbucketpro.s3.amazonaws.com/Joel.png" />
        Bild von Lukas Grüter
        </body>
        </html>